# Generated by Django 5.0.6 on 2024-07-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='staffs',
            field=models.ManyToManyField(related_name='consultations', to='main.staff'),
        ),
    ]
