# Generated by Django 5.0.6 on 2024-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_patient_medical_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
