# Generated by Django 5.0.6 on 2024-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='brief',
        ),
        migrations.AddField(
            model_name='consultation',
            name='medical_issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
