# Generated by Django 5.0.6 on 2024-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_consultation_brief_consultation_medical_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.TextField(blank=True, choices=[('undergoing_treatment', 'Undergoing Treatment'), ('fully_recovered', 'Fully Recovered')], null=True),
        ),
    ]
